# Generated by Django 3.1.5 on 2021-01-26 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=12)),
                ('created_st', models.DateTimeField(auto_now_add=True)),
                ('update_st', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_doc', models.CharField(max_length=3)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('comments', models.TextField()),
                ('created_proj', models.DateTimeField(auto_now_add=True)),
                ('update_proj', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pageformat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_format', models.CharField(max_length=15)),
                ('created_fm', models.DateTimeField(auto_now_add=True)),
                ('update_fm', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_page', models.CharField(max_length=3)),
                ('created_pt', models.DateTimeField(auto_now_add=True)),
                ('update_pt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_by_hh', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('cost_by_doc', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('cost_by_A1', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_status', models.CharField(max_length=50)),
                ('created_st', models.DateTimeField(auto_now_add=True)),
                ('update_st', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('created_sub', models.DateTimeField(auto_now_add=True)),
                ('update_sub', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arq', models.FileField(help_text='localizar Arquivo', upload_to='uploads/')),
                ('update_arq', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=255, verbose_name='NOME DO COLABORADOR')),
                ('emp_office', models.CharField(max_length=255, verbose_name='FUNÇÃO')),
                ('emp_contrato', models.CharField(max_length=20, verbose_name='CONTRATO')),
                ('photo', models.FileField(blank=True, null=True, upload_to='uploads/photos/', verbose_name='FOTO')),
                ('created_emp', models.DateTimeField(auto_now_add=True)),
                ('update_emp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USUÁRIO')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documment_name', models.CharField(max_length=255, verbose_name='NOME DOCUMENTO')),
                ('created_doc', models.DateTimeField(auto_now_add=True)),
                ('update_doc', models.DateTimeField(auto_now=True)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.doct', verbose_name='CÓDIGO DOC')),
                ('doc_type_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.paget', verbose_name='TIPO PÁGINA')),
                ('format_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.pageformat', verbose_name='FORMATO DO DOCUMENTO')),
            ],
        ),
        migrations.CreateModel(
            name='Cotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='NOME DOCUMENTO')),
                ('qt_page', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='QT PÁGINA')),
                ('qt_hh', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='QT HH')),
                ('cost_doc', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='CUSTO DOCUMENTO')),
                ('created_ct', models.DateTimeField(auto_now_add=True)),
                ('update_ct', models.DateTimeField(auto_now=True)),
                ('cod_doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.doct', verbose_name='CÓDIGO DOC')),
                ('doc_name_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.documentstandard', verbose_name='DOCUMENTO BASE')),
                ('format_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.pageformat', verbose_name='FORMATO')),
                ('page_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.paget', verbose_name='TIPO PÁGINA')),
                ('proj_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.myproject', verbose_name='PROJETO')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.subject', verbose_name='DISCIPLINA')),
            ],
        ),
    ]
