# Generated by Django 3.1.4 on 2021-01-28 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdProj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='NOME DOCUMENTO')),
                ('qt_page', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='QT PÁGINA')),
                ('status', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='STATUS_PROJETO')),
                ('date', models.DateField(auto_now=True)),
                ('created_ct', models.DateTimeField(auto_now_add=True)),
                ('update_ct', models.DateTimeField(auto_now=True)),
                ('aprov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprov', to='documentation.employee', verbose_name='APROVADOR')),
                ('cod_doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.doct', verbose_name='CÓDIGO DOC')),
                ('doc_name_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.documentstandard', verbose_name='DOCUMENTO BASE')),
                ('elab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elab', to='documentation.employee', verbose_name='ELABORADOR')),
                ('emiss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emiss', to='documentation.employee', verbose_name='EMISSOR')),
                ('format_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.pageformat', verbose_name='FORMATO')),
                ('page_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.paget', verbose_name='TIPO PÁGINA')),
                ('proj_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.myproject', verbose_name='PROJETO')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responseible', to='documentation.employee', verbose_name='RESPONSÁVEL')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.subject', verbose_name='DISCIPLINA')),
                ('verif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verif', to='documentation.employee', verbose_name='VERIFICADOR')),
            ],
        ),
    ]
