# Generated by Django 3.1.4 on 2021-01-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_ldproj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldproj',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
